.TH "ACP Basic Layer" 3 "Thu Aug 28 2014" "Version 1.0.0-rc1" "ACE Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ACP Basic Layer \- 
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBACP Basic Layer Infrastructure\fP"
.br
.ti -1c
.RI "\fBACP Basic Layer Global Memory Management\fP"
.br
.ti -1c
.RI "\fBACP Basic Layer Global Memory Access\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ACP basic layer is a thin abstraction of underlying communication devices\&.
.PP
The basic layer of ACP provides global address space shared among all of the processes\&. The global address of this space is represented by 64bit unsigned integer, so that it can be directly handled by the atomic operations of CPUs and devices\&. Any local memory space of any process can be mapped to this space via the registration function\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ACE Project from the source code\&.
