.TH "acp_wsditem" 3 "Thu Jun 2 2016" "Version 2.0.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acp_wsditem \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "size_t \fBsize_ws\fP"
.br
.ti -1c
.RI "size_t \fBsize_default\fP"
.br
.ti -1c
.RI "size_t \fBsize_remainder\fP"
.br
.ti -1c
.RI "size_t \fBngas\fP"
.br
.ti -1c
.RI "\fBacp_atkey_t\fP \fBkey_data\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP \fBga_data\fP"
.br
.ti -1c
.RI "\fBacp_atkey_t\fP * \fBkeys\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP * \fBgas\fP"
.br
.ti -1c
.RI "int * \fBprocs\fP"
.br
.ti -1c
.RI "int * \fBsizes\fP"
.br
.ti -1c
.RI "void * \fBdata\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
