.TH "acp_set_ib_t" 3 "Thu Jun 2 2016" "Version 2.0.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acp_set_ib_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBacp_set_it_t\fP \fBit\fP"
.br
.ti -1c
.RI "int \fBsuccess\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
