.TH "acpml" 3 "Thu Jun 2 2016" "Version 2.0.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acpml \- ACP Middle Layer
.SS "Modules"

.in +1c
.ti -1c
.RI "\fBACP Middle Layer Communication Library\fP"
.br
.ti -1c
.RI "\fBACP Middle Layer Data Library\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
ACP middle layer is a set of operations for primitive communication patterns used by applications\&.
.PP
\&.\&.\&.\&.\&.\&.\&.\&.\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
