.TH "acp_set_it_t" 3 "Thu Jun 2 2016" "Version 2.0.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acp_set_it_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBacp_set_t\fP \fBset\fP"
.br
.ti -1c
.RI "int \fBrank\fP"
.br
.ti -1c
.RI "int \fBslot\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP \fBelem\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
