.TH "acp_map_it_t" 3 "Thu Nov 12 2015" "Version 1.2.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acp_map_it_t \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBacp_map_t\fP \fBmap\fP"
.br
.ti -1c
.RI "int \fBrank\fP"
.br
.ti -1c
.RI "int \fBslot\fP"
.br
.ti -1c
.RI "\fBacp_ga_t\fP \fBelem\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
