.TH "acp_map_t" 3 "Thu Nov 12 2015" "Version 1.2.0" "ACP Library" \" -*- nroff -*-
.ad l
.nh
.SH NAME
acp_map_t \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <acp\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "\fBacp_ga_t\fP \fBga\fP"
.br
.ti -1c
.RI "uint64_t \fBnum_ranks\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Represents that no map type data does NOT exist\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for ACP Library from the source code\&.
